#!/usr/bin/env python3
"""
gen.py — Record an action sequence against the live app, then execute it to
         take screenshots and render out/demo.mp4.

GUIDED MODE (default):  python3 demo/gen.py
  Open Cyclemetry (pnpm dev) first. Origin is auto-detected from the window —
  no mouse-to-corner step. gen.py walks the fixed STORYBOARD; for each prompted
  step, point the mouse at the named UI element and press SPACE. Labels and
  action types are fixed, so the captured shots always match Demo.tsx.

  [space]/[c]  capture current step      [b]  back one step
  [r]          restart from step 1       [g]  go (execute + render)
  [q]          quit without running

FREE MODE (advanced):  python3 demo/gen.py free
  Old free-form recorder — type your own labels/actions.
  [o] origin  [s]hot  [h]over  [c]lick  [d]rag↓  [e]nd↑  [u]ndo  [g]o  [q]uit

Phase 2 – execute (automatic):
  Drives the live app through the recorded sequence, saves numbered screenshots
  to public/shots/, regenerates src/shots.generated.ts, verifies the shot set
  against Demo.tsx, then runs `npm run render`.
  Also prints const PT_N = wc(...) declarations for Demo.tsx.
"""

import curses
import sys
import time
import re
import subprocess
import ctypes
from pathlib import Path

# ── Quartz (needed for execution phase) ────────────────────────────────────
try:
    import Quartz
    HAS_QUARTZ = True
except ImportError:
    HAS_QUARTZ = False

# ── CoreGraphics mouse-read (no pip required) ───────────────────────────────
class _CGPoint(ctypes.Structure):
    _fields_ = [("x", ctypes.c_double), ("y", ctypes.c_double)]

try:
    _CG = ctypes.CDLL("/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics")
    _CG.CGEventCreate.restype        = ctypes.c_void_p
    _CG.CGEventCreate.argtypes       = [ctypes.c_void_p]
    _CG.CGEventGetLocation.restype   = _CGPoint
    _CG.CGEventGetLocation.argtypes  = [ctypes.c_void_p]
    _CG.CFRelease.restype            = None
    _CG.CFRelease.argtypes           = [ctypes.c_void_p]

    def get_mouse() -> tuple[int, int]:
        ev = _CG.CGEventCreate(None)
        pt = _CG.CGEventGetLocation(ev)
        _CG.CFRelease(ev)
        return int(pt.x), int(pt.y)

    get_mouse()  # smoke-test
except Exception as e:
    print(f"CoreGraphics load failed: {e}")
    sys.exit(1)

# ── Paths ───────────────────────────────────────────────────────────────────
ROOT     = Path(__file__).parent
SHOTS      = ROOT / "public" / "shots"
DEMO_TSX   = ROOT / "src" / "Demo.tsx"
MANIFEST   = ROOT / "src" / "shots.generated.ts"
WIN_CONFIG = ROOT / "src" / "window.generated.ts"

# ── Shot bookkeeping ─────────────────────────────────────────────────────────
def required_shots() -> list[str]:
    """Shot files Demo.tsx expects, parsed straight from its staticFile() calls
    so Demo.tsx stays the single source of truth."""
    try:
        txt = DEMO_TSX.read_text()
    except OSError:
        return []
    # matches shot("11_click.png") and staticFile("shots/11_click.png")
    names = re.findall(r'shots/([\w.\-]+\.png)', txt)
    names += re.findall(r'\bshot\(\s*"([\w.\-]+\.png)"', txt)
    return sorted(set(names))

def captured_shots() -> list[str]:
    return sorted(f.name for f in SHOTS.glob("*.png"))

def write_window_config(win_w: int, win_h: int) -> None:
    """Write actual logical window dimensions for Demo.tsx / Root.tsx canvas sizing."""
    # H264 requires even dimensions — clamp down if needed
    if win_w % 2 != 0 or win_h % 2 != 0:
        fixed_w = win_w - (win_w % 2)
        fixed_h = win_h - (win_h % 2)
        print(f"  ⚠️   odd dimension detected ({win_w}×{win_h}) — H264 requires even dims")
        print(f"       auto-clamped to {fixed_w}×{fixed_h}")
        win_w, win_h = fixed_w, fixed_h
    WIN_CONFIG.write_text(
        "// AUTO-GENERATED by gen.py — do not edit by hand.\n"
        "// Actual Cyclemetry window logical dimensions at record time.\n"
        "// Demo.tsx and Root.tsx use these to derive the correct canvas size and wc() scale.\n"
        f"export const WIN_W = {win_w};\n"
        f"export const WIN_H = {win_h};\n"
    )
    print(f"  📐  window config: {win_w}×{win_h}")

def write_manifest() -> None:
    """Regenerate src/shots.generated.ts to reflect what's in public/shots/."""
    files = captured_shots()
    lines = ",\n".join(f'  "{n}"' for n in files)
    MANIFEST.write_text(
        "// AUTO-GENERATED by gen.py — do not edit by hand.\n"
        "// Lists the screenshot files currently present in public/shots/.\n"
        "// Demo.tsx uses this to fall back gracefully when a shot is missing.\n"
        "export const AVAILABLE_SHOTS: string[] = [\n"
        + (lines + ",\n" if lines else "")
        + "];\n"
    )
    print(f"  📝  wrote manifest ({len(files)} shot{'s' if len(files) != 1 else ''})")

def verify_shots() -> bool:
    """Compare captured shots against Demo.tsx's requirements. Returns True if OK."""
    req = required_shots()
    have = set(captured_shots())
    missing = [n for n in req if n not in have]
    extra   = sorted(n for n in have if n not in set(req))
    if missing:
        print("\n⚠️  Missing shots required by Demo.tsx:")
        for n in missing:
            print(f"      • {n}")
    if extra:
        print("\nℹ️  Captured shots not used by Demo.tsx (wrong label/action?):")
        for n in extra:
            print(f"      • {n}")
    return not missing

# ── Action type metadata ────────────────────────────────────────────────────
#   key  → (type_name,  display,   needs_coords)
ACTIONS = {
    "s": ("shot",       "SHOT    ", False),
    "h": ("hover",      "HOVER   ", True),
    "c": ("click",      "CLICK   ", True),
    "d": ("drag_start", "DRAG↓   ", True),
    "e": ("drag_end",   "DRAG↑   ", True),
}

# ── Canonical storyboard ─────────────────────────────────────────────────────
# The fixed action sequence Demo.tsx renders. Guided mode walks these in order
# so labels/action types never drift. Labels are auto-derived as {idx:02d}_{type}
# to match Demo.tsx's getShot() expectations — verify_shots() enforces the match.
#   (action_type, prompt describing the UI element to point at)
STORYBOARD = [
    ("click",      "Open Template button"),
    ("click",      "Select template in the picker"),
    ("click",      "Open Activity button"),
    ("click",      "Activate the file picker"),
    ("click",      "Select the activity file"),
    ("click",      "Confirm activity"),
    ("drag_start", "Drag-START handle — GRAB it (mouse down point)"),
    ("drag_end",   "Drag-START handle — RELEASE here (drag to)"),
    ("drag_start", "Drag-END handle — GRAB it (mouse down point)"),
    ("drag_end",   "Drag-END handle — RELEASE here (drag to)"),
    ("click",      "Render button"),
]

# ── Window detection ────────────────────────────────────────────────────────
def get_win() -> tuple[int, int, int, int, int] | None:
    if not HAS_QUARTZ:
        return None
    opts = (Quartz.kCGWindowListOptionOnScreenOnly |
            Quartz.kCGWindowListExcludeDesktopElements)
    for w in Quartz.CGWindowListCopyWindowInfo(opts, Quartz.kCGNullWindowID):
        name = str(w.get("kCGWindowOwnerName", "")).lower()
        if "cyclemetry" in name and w.get("kCGWindowLayer", 99) == 0:
            b = w["kCGWindowBounds"]
            return (w["kCGWindowNumber"],
                    int(b["X"]), int(b["Y"]),
                    int(b["Width"]), int(b["Height"]))
    return None

# ── Low-level mouse events ──────────────────────────────────────────────────
def _post(kind, x, y):
    pt  = Quartz.CGPoint(x, y)
    evt = Quartz.CGEventCreateMouseEvent(None, kind, pt, Quartz.kCGMouseButtonLeft)
    Quartz.CGEventPost(Quartz.kCGHIDEventTap, evt)

def _move(x, y):  _post(Quartz.kCGEventMouseMoved,       x, y); time.sleep(0.02)
def _drag(x, y):  _post(Quartz.kCGEventLeftMouseDragged, x, y); time.sleep(0.02)

def smooth(x0, y0, x1, y1, held=False, steps=22, dur=0.35):
    fn = _drag if held else _move
    for i in range(steps + 1):
        t = i / steps
        t = t * t * (3 - 2 * t)   # smoothstep
        fn(int(x0 + (x1 - x0) * t), int(y0 + (y1 - y0) * t))
        time.sleep(dur / steps)

def click(sx, sy):
    _move(sx, sy);                              time.sleep(0.05)
    _post(Quartz.kCGEventLeftMouseDown, sx, sy); time.sleep(0.08)
    _post(Quartz.kCGEventLeftMouseUp,   sx, sy); time.sleep(0.12)

def activate():
    # Activate the already-running window by PID (works for dev app too)
    opts = (Quartz.kCGWindowListOptionOnScreenOnly |
            Quartz.kCGWindowListExcludeDesktopElements)
    for w in Quartz.CGWindowListCopyWindowInfo(opts, Quartz.kCGNullWindowID):
        name = str(w.get("kCGWindowOwnerName", "")).lower()
        if "cyclemetry" in name and w.get("kCGWindowLayer", 99) == 0:
            pid = w.get("kCGWindowOwnerPID")
            if pid:
                subprocess.run(
                    ["osascript", "-e",
                     f'tell application "System Events" to set frontmost of '
                     f'first process whose unix id is {pid} to true'],
                    capture_output=True,
                )
                time.sleep(0.3)
                return
    # fallback: try by name (may launch build app)
    subprocess.run(
        ["osascript", "-e", 'tell application "Cyclemetry" to activate'],
        capture_output=True,
    )
    time.sleep(0.3)

def take_shot(wid: int, name: str):
    SHOTS.mkdir(exist_ok=True)
    path = str(SHOTS / f"{name}.png")
    subprocess.run(["screencapture", "-l", str(wid), "-o", path], capture_output=True)
    kb = (SHOTS / f"{name}.png").stat().st_size // 1024
    print(f"  📸  {name}.png  ({kb} KB)")

# ── Guided record phase ──────────────────────────────────────────────────────
def guided_phase(scr) -> tuple[tuple[int, int] | None, list[dict]]:
    """Walk the fixed STORYBOARD. Origin auto-detected; user just points the
    mouse at each prompted element and presses SPACE. Labels/types are fixed,
    so the captured shot set always matches Demo.tsx."""
    curses.curs_set(0)
    scr.timeout(80)
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(1, curses.COLOR_RED,    -1)
    curses.init_pair(2, curses.COLOR_CYAN,   -1)
    curses.init_pair(3, curses.COLOR_GREEN,  -1)
    curses.init_pair(4, curses.COLOR_YELLOW, -1)
    RED, CYAN, GREEN, YELLOW = (curses.color_pair(i) for i in (1, 2, 3, 4))
    DIM, BOLD = curses.A_DIM, curses.A_BOLD

    win = get_win()
    if not win:
        return None, []
    _, ox, oy, _, _ = win
    origin = (ox, oy)

    actions: list[dict] = []
    i = 0
    status, status_ttl = "", 0

    def flash(msg):
        nonlocal status, status_ttl
        status, status_ttl = msg, 25

    while True:
        sx, sy = get_mouse()
        wx, wy = sx - origin[0], sy - origin[1]
        h, w   = scr.getmaxyx()
        W      = min(w - 1, 70)
        scr.erase()

        def put(row, col, text, attr=0):
            try: scr.addstr(row, col, text[:W - col], attr)
            except curses.error: pass

        put(0, 0, "━" * W, RED)
        put(1, 2, "GUIDED RECORD", BOLD)
        put(1, 18, f"origin auto ({ox}, {oy})", DIM)
        put(2, 0, "━" * W, RED)

        if i < len(STORYBOARD):
            atype, desc = STORYBOARD[i]
            label = f"{i + 1:02d}_{atype}"
            disp  = next(v[1] for v in ACTIONS.values() if v[0] == atype)
            put(4, 2, f"STEP {i + 1}/{len(STORYBOARD)}", YELLOW | BOLD)
            put(4, 16, f"{disp.strip()}", GREEN | BOLD)
            put(5, 2, f"→ {desc}", BOLD)
            put(7, 2, f"screen ({sx:5d}, {sy:5d})", DIM)
            put(8, 2, f"window ({wx:5d}, {wy:5d})", CYAN)
            put(9, 2, f"wc({wx}, {wy})  →  {label}.png"
                       if atype != "drag_start" else
                       f"wc({wx}, {wy})  →  {label} (no shot)", RED | BOLD)
        else:
            put(4, 2, "✓ all steps captured", GREEN | BOLD)
            put(5, 2, "press [g] to execute + render, or [b] to redo last", BOLD)

        # captured list
        put(11, 0, "─" * W, DIM)
        put(11, 2, f"captured ({len(actions)})", DIM)
        for rel, a in enumerate(actions[-(h - 17):]):
            idx = len(actions) - min(len(actions), h - 17) + rel
            tag = "drag" in a["type"] and YELLOW or GREEN
            cs  = f"wc({a['wx']}, {a['wy']})" if a["wx"] is not None else "—"
            put(12 + rel, 2, f"{idx+1:02d}  {a['type']:<11} {cs}", tag)

        put(h - 3, 0, "─" * W, DIM)
        put(h - 2, 1, "[space]/[c] capture   [b]ack   [r]estart   [g]o   [q]uit", DIM)
        if status and status_ttl > 0:
            put(h - 1, 2, status, GREEN); status_ttl -= 1
        scr.refresh()

        ch = scr.getch()
        if ch == ord("q"):
            return None, []
        elif ch == ord("r"):
            actions, i = [], 0
            flash("restarted")
        elif ch == ord("b"):
            if actions:
                actions.pop(); i -= 1
                flash(f"back to step {i + 1}")
            else:
                flash("nothing to undo")
        elif ch == ord("g"):
            if i >= len(STORYBOARD) and HAS_QUARTZ:
                return origin, actions
            elif not HAS_QUARTZ:
                flash("pip3 install pyobjc-framework-Quartz")
            else:
                flash(f"capture all {len(STORYBOARD)} steps first ({i} done)")
        elif ch in (ord(" "), ord("c"), ord("\n"), curses.KEY_ENTER):
            if i >= len(STORYBOARD):
                flash("done — press [g] to go")
                continue
            atype, _ = STORYBOARD[i]
            cap_sx, cap_sy = get_mouse()
            actions.append({
                "type":  atype,
                "label": f"{i + 1:02d}_{atype}",
                "wx":    cap_sx - origin[0],
                "wy":    cap_sy - origin[1],
            })
            i += 1
            flash(f"✓ step {i} captured")
            if i >= len(STORYBOARD):
                flash("✓ all steps done — press [g] to execute")

# ── Record phase (free-form) ──────────────────────────────────────────────────
def record_phase(scr) -> tuple[tuple[int, int] | None, list[dict]]:
    curses.curs_set(0)
    scr.timeout(80)
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(1, curses.COLOR_RED,    -1)
    curses.init_pair(2, curses.COLOR_CYAN,   -1)
    curses.init_pair(3, curses.COLOR_GREEN,  -1)
    curses.init_pair(4, curses.COLOR_YELLOW, -1)

    RED    = curses.color_pair(1)
    CYAN   = curses.color_pair(2)
    GREEN  = curses.color_pair(3)
    YELLOW = curses.color_pair(4)
    DIM    = curses.A_DIM
    BOLD   = curses.A_BOLD

    origin:  tuple[int, int] | None = None
    actions: list[dict]             = []
    status   = ""
    status_ttl = 0

    def flash(msg: str):
        nonlocal status, status_ttl
        status = msg; status_ttl = 25

    def prompt_label(default: str) -> str:
        curses.echo(); curses.curs_set(1)
        h, w = scr.getmaxyx()
        W = min(w - 1, 64)
        scr.addstr(h - 1, 0, " " * W)
        scr.addstr(h - 1, 2, "label: ", BOLD)
        scr.clrtoeol()
        scr.refresh()
        try:
            raw = scr.getstr(h - 1, 9, 32)
            return raw.decode().strip() or default
        except Exception:
            return default
        finally:
            curses.noecho()
            curses.curs_set(0)

    while True:
        sx, sy = get_mouse()
        h, w   = scr.getmaxyx()
        W      = min(w - 1, 64)
        scr.erase()

        def put(row, col, text, attr=0):
            try: scr.addstr(row, col, text[:W - col], attr)
            except curses.error: pass

        # header
        put(0, 0, "━" * W, RED)
        put(1, 2, "GEN", BOLD)
        put(1, 8, "record → execute → render", DIM)
        put(2, 0, "━" * W, RED)

        # live coords
        put(4, 2, f"screen  ({sx:5d}, {sy:5d})", DIM)
        if origin:
            wx_live = sx - origin[0]
            wy_live = sy - origin[1]
            put(5, 2, f"window  ({wx_live:5d}, {wy_live:5d})", CYAN)
            put(6, 2, f"wc({wx_live}, {wy_live})", RED | BOLD)
        else:
            put(5, 2, "window  — press [o] to set origin first", DIM)

        # sequence list
        put(8, 0, "─" * W, DIM)
        header = f"sequence ({len(actions)} action{'s' if len(actions) != 1 else ''})"
        put(8, 2, header, DIM)

        visible_start = max(0, len(actions) - (h - 14))
        for rel, a in enumerate(actions[visible_start:]):
            row = 9 + rel
            if row >= h - 4:
                break
            i        = visible_start + rel
            atype    = a["type"]
            _, disp, has_coords = ACTIONS.get(
                next(k for k, v in ACTIONS.items() if v[0] == atype), ("","",False)
            )
            coord_str = f"wc({a['wx']}, {a['wy']})" if has_coords else "—"
            color = YELLOW if "drag" in atype else GREEN
            put(row, 2, f"{i+1:02d}  {disp}  {a['label']:<24}  {coord_str}", color)

        # controls / status
        put(h - 3, 0, "─" * W, DIM)
        controls = "[o]rigin  [s]hot  [h]over  [c]lick  [d]rag↓  [e]nd↑  [u]ndo  [g]o  [q]uit"
        put(h - 2, 1, controls, DIM)
        if status and status_ttl > 0:
            put(h - 1, 2, status, GREEN)
            status_ttl -= 1

        scr.refresh()
        ch = scr.getch()

        if ch == ord("q"):
            return None, []

        elif ch == ord("o"):
            win = get_win()
            if win:
                _, wx0, wy0, _, _ = win
                origin = (wx0, wy0)
                flash(f"✓ origin auto-detected at ({wx0}, {wy0})")
            else:
                origin = (sx, sy)
                flash(f"✓ origin set at mouse ({sx}, {sy}) — Cyclemetry not found, using mouse")

        elif ch == ord("u"):
            if actions:
                r = actions.pop()
                flash(f"✗ removed [{r['type']}] {r['label']}")
            else:
                flash("Nothing to undo")

        elif ch == ord("g"):
            if not origin:
                flash("Set origin first — press [o]")
            elif not actions:
                flash("No actions recorded yet")
            elif not HAS_QUARTZ:
                flash("pip3 install pyobjc-framework-Quartz  then retry")
            else:
                return origin, actions

        elif chr(ch) if 0 < ch < 128 else None in ACTIONS:
            key = chr(ch) if 0 < ch < 128 else None
            if key not in ACTIONS:
                continue

            _, _, needs_coords = ACTIONS[key]
            atype, _, _        = ACTIONS[key]

            if not origin:
                flash("Set origin first — press [o]")
                continue

            # Capture position NOW before the user moves to type
            cap_sx, cap_sy = get_mouse()
            wx = cap_sx - origin[0]
            wy = cap_sy - origin[1]

            idx     = len(actions) + 1
            default = f"{idx:02d}_{atype}"
            label   = prompt_label(default)

            actions.append({
                "type":  atype,
                "label": label,
                "wx":    wx if needs_coords else None,
                "wy":    wy if needs_coords else None,
            })

            if needs_coords:
                flash(f"✓ [{atype}] {label}  wc({wx}, {wy})")
            else:
                flash(f"✓ [{atype}] {label}")

    return None, []

# ── Execute phase ───────────────────────────────────────────────────────────
def execute(actions: list[dict]) -> None:
    result = get_win()
    if not result:
        print("❌  Cyclemetry window not found — open the app first")
        sys.exit(1)
    wid, win_x, win_y, win_w, win_h = result
    print(f"Window #{wid}: ({win_x},{win_y}) {win_w}×{win_h}\n")

    write_window_config(win_w, win_h)

    # Clear existing shots
    SHOTS.mkdir(exist_ok=True)
    for f in SHOTS.glob("*.png"):
        f.unlink()

    activate()
    time.sleep(0.5)

    # Convert window-relative coords to absolute screen coords
    def sc(wx, wy):
        return win_x + wx, win_y + wy

    prev_sx = win_x + win_w // 2
    prev_sy = win_y + win_h // 2
    held    = False
    hold_sx = hold_sy = 0

    for i, a in enumerate(actions):
        atype = a["type"]
        label = a["label"]
        asx, asy = sc(a["wx"], a["wy"]) if a["wx"] is not None else (prev_sx, prev_sy)

        _, disp, _ = ACTIONS[next(k for k, v in ACTIONS.items() if v[0] == atype)]
        print(f"  [{i+1:02d}] {disp.strip():<10}  {label}")

        if atype == "shot":
            time.sleep(0.3)
            take_shot(wid, label)

        elif atype == "hover":
            smooth(prev_sx, prev_sy, asx, asy)
            time.sleep(0.15)
            take_shot(wid, label)
            prev_sx, prev_sy = asx, asy

        elif atype == "click":
            smooth(prev_sx, prev_sy, asx, asy)
            time.sleep(0.08)
            click(asx, asy)
            time.sleep(0.6)
            take_shot(wid, label)
            prev_sx, prev_sy = asx, asy

        elif atype == "drag_start":
            smooth(prev_sx, prev_sy, asx, asy)
            time.sleep(0.05)
            _post(Quartz.kCGEventLeftMouseDown, asx, asy)
            time.sleep(0.08)
            held    = True
            hold_sx = asx
            hold_sy = asy
            prev_sx, prev_sy = asx, asy

        elif atype == "drag_end":
            smooth(hold_sx, hold_sy, asx, asy, held=True)
            _post(Quartz.kCGEventLeftMouseUp, asx, asy)
            held = False
            time.sleep(0.4)
            take_shot(wid, label)
            prev_sx, prev_sy = asx, asy

    shot_count = sum(1 for a in actions if a["type"] != "drag_start")
    print(f"\n✅  {shot_count} shots saved to public/shots/\n")

    # Keep src/shots.generated.ts in sync with what was actually captured
    write_manifest()

    # Patch PT_N coordinates in Demo.tsx — keeps cursor positions in sync with shots
    # Maps storyboard step order to the variable names Demo.tsx actually uses.
    PT_NAMES = ["PT_1", "PT_2", "PT_3", "PT_4", "PT_5", "PT_6",
                "PT_8", "PT_9", "PT_10", "PT_11", "PT_12"]
    coord_actions = [a for a in actions if a["wx"] is not None]
    if coord_actions:
        txt = DEMO_TSX.read_text()
        patched = 0
        for name, a in zip(PT_NAMES, coord_actions):
            new_txt = re.sub(
                rf'(const {re.escape(name)}\s*=\s*wc\()([^)]+)(\))',
                rf'\g<1>{a["wx"]}, {a["wy"]}\g<3>',
                txt,
            )
            if new_txt != txt:
                patched += 1
            txt = new_txt
        DEMO_TSX.write_text(txt)
        print(f"  ✏️   patched {patched}/{len(coord_actions)} PT_ coords in Demo.tsx")
        print("── wc() coords applied " + "─" * 37)
        for name, a in zip(PT_NAMES, coord_actions):
            print(f"  {name:<8} = wc({a['wx']}, {a['wy']})  // {a['label']}")
        print()

# ── Render ──────────────────────────────────────────────────────────────────
def run_render() -> None:
    print("── rendering " + "─" * 48)
    result = subprocess.run(["npm", "run", "render"], cwd=ROOT)
    if result.returncode == 0:
        print("\n✅  out/demo.mp4 ready")
    else:
        print("\n❌  render failed — check output above")
        sys.exit(1)

# ── Entry point ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    free_mode = "free" in sys.argv[1:]
    if free_mode:
        origin, actions = curses.wrapper(record_phase)
    else:
        if get_win() is None:
            print("❌  Cyclemetry window not found — open the app (pnpm dev) first.")
            sys.exit(1)
        origin, actions = curses.wrapper(guided_phase)
    if not actions:
        sys.exit(0)

    print(f"\n═══ executing {len(actions)} actions ═══\n")
    execute(actions)

    if not verify_shots():
        print(
            "\n❌  Render skipped — the captured shots don't match Demo.tsx.\n"
            "    Re-record the full sequence (default labels) so every required\n"
            "    shot is produced, then run again. Demo.tsx expects, in order:\n"
            "      6× click → drag↓/drag↑ → drag↓/drag↑ → click\n"
            "    (accept the default label at each prompt by pressing Enter).\n"
        )
        sys.exit(1)

    print()
    run_render()
