#!/usr/bin/env python3
"""
probe.py — Read public/screen.mov and write src/recording.generated.ts.

Run this once after dropping a new recording at public/screen.mov:

    python3 demo/probe.py

It records the recording's native resolution, frame rate, and length so the
Remotion composition (Root.tsx) sizes itself to match the footage exactly.
Requires ffprobe (brew install ffmpeg).
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SCREEN = ROOT / "public" / "screen.mov"
OUT = ROOT / "src" / "recording.generated.ts"


def main() -> None:
    if not SCREEN.exists():
        sys.exit(f"❌  No recording found at {SCREEN}\n"
                 f"    Record the app session and save it there as screen.mov first.")

    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        sys.exit("❌  ffprobe not found — install with: brew install ffmpeg")

    proc = subprocess.run(
        [ffprobe, "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=width,height,r_frame_rate",
         "-show_entries", "format=duration",
         "-of", "json", str(SCREEN)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        sys.exit(f"❌  ffprobe failed:\n{proc.stderr}")

    data = json.loads(proc.stdout)
    stream = data["streams"][0]
    width = int(stream["width"])
    height = int(stream["height"])

    num, den = stream["r_frame_rate"].split("/")
    fps_exact = float(num) / float(den)
    fps = round(fps_exact)  # composition fps must be a clean integer

    duration = float(data["format"]["duration"])
    source_frames = round(duration * fps)

    # h264 requires even dimensions — clamp down if the recording is odd.
    even_w = width - (width % 2)
    even_h = height - (height % 2)
    if (even_w, even_h) != (width, height):
        print(f"  ⚠️   odd dimension ({width}×{height}) — clamped to {even_w}×{even_h}")

    OUT.write_text(
        "// AUTO-GENERATED by probe.py — do not edit by hand.\n"
        "// Run `python3 demo/probe.py` after dropping your recording at public/screen.mov.\n"
        "// These are the raw properties of the source recording.\n"
        f"export const WIDTH = {even_w};\n"
        f"export const HEIGHT = {even_h};\n"
        f"export const FPS = {fps};\n"
        f"export const SOURCE_FRAMES = {source_frames};\n"
    )

    print(f"  📐  {even_w}×{even_h} @ {fps}fps")
    print(f"  ⏱   {duration:.2f}s  →  {source_frames} source frames")
    print(f"  📝  wrote {OUT.relative_to(ROOT)}")
    print("\n  Next: tune SEGMENTS / CLICKS in src/timeline.ts, then `npm run render`.")


if __name__ == "__main__":
    main()
