// AUTO-GENERATED by probe.py — do not edit by hand.
// Run `python3 demo/probe.py` after dropping your recording at public/screen.mov.
// These are the raw properties of the source recording.
export const WIDTH = 2492;
export const HEIGHT = 1790;
export const FPS = 60;
export const SOURCE_FRAMES = 6851;
