// AUTO-GENERATED by record.py — do not edit by hand.
// Speed segments derived from the actions record.py drove: real-time at
// each click/hover/drag, DEFAULT_SPEED everywhere else.
import type { SpeedSegment } from './timeline';

export const GEN_DEFAULT_SPEED = 2;

// Seconds added to every segment. Nudge by ±0.1 and re-render if the
// slow-down windows feel early or late relative to the cursor.
export const GEN_SYNC_OFFSET = 0;

export const GEN_SEGMENTS: SpeedSegment[] = [
  { fromSec: 0.474, toSec: 1.174, speed: 1 },
  { fromSec: 1.696, toSec: 2.396, speed: 1 },
  { fromSec: 2.899, toSec: 3.599, speed: 1 },
  { fromSec: 4.117, toSec: 4.817, speed: 1 },
  { fromSec: 5.662, toSec: 6.812, speed: 1 },
  { fromSec: 6.891, toSec: 8.035, speed: 1 },
  { fromSec: 7.78, toSec: 8.48, speed: 1 },
  { fromSec: 8.992, toSec: 9.692, speed: 1 },
  { fromSec: 10.209, toSec: 10.909, speed: 1 },
  { fromSec: 11.421, toSec: 12.121, speed: 1 },
  { fromSec: 12.628, toSec: 13.328, speed: 1 },
];
