// ─────────────────────────────────────────────────────────────────────────────
// timeline.ts — the ONE file you edit to tune the demo.
//
// The demo plays a single real screen recording (public/screen.mov) and speeds
// it up non-uniformly: fast through the boring parts, normal speed at the clicks.
// It also overlays synthetic click rings on top of the real cursor.
//
// All times below are in SOURCE seconds (where they land in your raw recording,
// i.e. what you see when scrubbing screen.mov), and all coordinates are in SOURCE
// pixels (the recording's native resolution — see recording.generated.ts WIDTH/HEIGHT).
// ─────────────────────────────────────────────────────────────────────────────
import { FPS, SOURCE_FRAMES, WIDTH, HEIGHT } from "./recording.generated";
import {
  GEN_DEFAULT_SPEED,
  GEN_SYNC_OFFSET,
  GEN_SEGMENTS,
} from "./timeline.generated";

// ── Output resolution ────────────────────────────────────────────────────────
// SCALE downscales the composition (1 = native recording res). Lower it if renders
// are slow; click coordinates below stay in source px and are scaled automatically.
export const SCALE = 1;

const even = (n: number) => Math.max(2, Math.round(n / 2) * 2); // h264 needs even dims
export const CANVAS_W = even(WIDTH * SCALE);
export const CANVAS_H = even(HEIGHT * SCALE);

// ── Speed remap ───────────────────────────────────────────────────────────────
// These are generated by `record.py` from the actions it drove (slow at clicks,
// fast in between). DEFAULT_SPEED applies everywhere not covered by a segment.
// Add hand-tuned overrides to MANUAL_SEGMENTS below — they win over generated ones.
export type SpeedSegment = { fromSec: number; toSec: number; speed: number };

export const DEFAULT_SPEED = GEN_DEFAULT_SPEED;

const MANUAL_SEGMENTS: SpeedSegment[] = [
  // { fromSec: 8.0, toSec: 12.0, speed: 4 },  // blast through a boring stretch
];

// Generated segments are shifted by the same sync offset as the clicks.
export const SEGMENTS: SpeedSegment[] = [
  ...MANUAL_SEGMENTS,
  ...GEN_SEGMENTS.map((s) => ({
    fromSec: s.fromSec + GEN_SYNC_OFFSET,
    toSec: s.toSec + GEN_SYNC_OFFSET,
    speed: s.speed,
  })),
];

// ─────────────────────────────────────────────────────────────────────────────
// Below here is machinery — you shouldn't need to touch it.
// ─────────────────────────────────────────────────────────────────────────────

function speedAtSourceFrame(sf: number): number {
  const t = sf / FPS;
  for (const s of SEGMENTS) {
    if (t >= s.fromSec && t < s.toSec) return s.speed;
  }
  return DEFAULT_SPEED;
}

// Build the output-frame → source-frame map once. Each source frame occupies
// (1 / speed) output frames, so faster segments consume fewer output frames.
function buildFrameMap(): number[] {
  const map: number[] = [];
  let acc = 0;
  for (let sf = 0; sf < SOURCE_FRAMES; sf++) {
    acc += 1 / Math.max(0.01, speedAtSourceFrame(sf));
    const target = Math.round(acc);
    while (map.length < target) map.push(sf);
  }
  if (map.length === 0) map.push(0);
  return map;
}

export const FRAME_MAP = buildFrameMap();
export const OUTPUT_FPS = FPS; // keep composition fps == source fps so startFrom math is 1:1
export const MAIN_DURATION_IN_FRAMES = FRAME_MAP.length;

// ── Final rendered video outro ───────────────────────────────────────────────
// Drop the provided final render in public/ and point OUTRO_VIDEO_FILE at it.
// Remotion will append the first three seconds after the recorded click flow.
export const OUTRO_VIDEO_FILE = "demo_vid.mov";
export const OUTRO_DURATION_SECONDS = 3;
export const OUTRO_DURATION_IN_FRAMES = Math.round(
  OUTRO_DURATION_SECONDS * OUTPUT_FPS,
);
export const OUTRO_REVEAL_IN_FRAMES = Math.round(0.6 * OUTPUT_FPS);
export const DURATION_IN_FRAMES =
  MAIN_DURATION_IN_FRAMES + OUTRO_DURATION_IN_FRAMES;

// Source frame shown at a given output (composition) frame.
export function sourceFrameAt(outFrame: number): number {
  const i = Math.max(0, Math.min(Math.round(outFrame), FRAME_MAP.length - 1));
  return FRAME_MAP[i];
}

// OffthreadVideo shows source frame = (compFrame + startFrom) at playbackRate 1.
// So to show sourceFrameAt(f) we pass startFrom = sourceFrameAt(f) - f (clamped ≥ 0).
export function startFromAt(outFrame: number): number {
  return Math.max(0, sourceFrameAt(outFrame) - Math.round(outFrame));
}
